### ISSUE TITLE
Broken link through all the pages and posts

### ISSUE THREAD

**Issue by hieulq** [vietstack/vietstack.github.io.bka#38]
The past commits defined wrong and not heterogeneous URL of vietstack in all pages and posts e.g: follow us in twitter vietstacker but in twitter link of footer is vietstack.

Please fix them all.

**Comment by congto** [comment]
@hieulq 

Plz https://github.com/vietstack/vietstack.github.io/pull/70

**Comment by vietstack** [comment]
there are only one error left: youtube channel link, please fix it @congto
