### ISSUE TITLE
Ads in landing page

### ISSUE THREAD

**Issue by hieulq** [vietstack/vietstack.github.io.bka#39]
Please remove all ads in all posts/pages.

**Comment by hieulq** [comment]
Removed google ads script in default.html template in _layouts folder, please recheck and _leave comment here_.

If no problems are found, we will close this bug.

**Comment by hieulq** [comment]
@congto closing this bug mean "no ads found", if any ads happen, please take responsibility for solving the problem.

**Comment by vietstack** [comment]
@hieulq oke

**Comment by vietstack** [comment]
reopen because mess of conflict commits.
commented by hieulq.

**Comment by vietstack** [comment]
re-close after cleaning the mesh.
