### ISSUE TITLE
Too long URI because of many categorized tags

### ISSUE THREAD

**Issue by hieulq** [vietstack/vietstack.github.io.bka#44]
You create post with too many categorized tags (including english and vietnamese) that can absolutely make URI too long.

For example: post A with categories: [test, ế] can generate a URI like: http://vietstack.github.io/test/ế/<name of post>

Please arrange and use one tag per post for easier reading.

**Comment by hieulq** [comment]
@congto saw that you are rolling in this task, so please take care of this issue before submitting new converted posts.

**Comment by congto** [comment]
@hieulq done

https://vietstack.github.io/tech/overview-of-benchmark-in-cloud-and-benchmark-as-a-service-rally/
https://vietstack.github.io/vietstack/duc-rut-vai-kinh-nghiem-ca-nhan-khi-tim-hieu-ve-openstack/
