### ISSUE TITLE
Page build error

### ISSUE THREAD

**Issue by hieulq** [vietstack/vietstack.github.io.bka#56]
Page build error from commit 2803cbd03ac1cf93ebb6166ff50004dfb0d6fc40. Please check jekyll log.

**Comment by congto** [comment]
@hieulq 

xóa các bài mẫu sẵn có đi thì bị lỗi. méo hiểu nó quy định như nào cho thư mục `_post`

**Comment by vietstack** [comment]
close because of broken reference @congto did.
